//
//  OpenDoorViewController.swift
//  Door Opener
//
//  Created by Luka Usalj on 16/05/16.
//  Copyright (c) 2016 FER. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

// MARK: -  OpenDoor View Controller -
final class OpenDoorViewController: UIViewController {
    let animationDuration = 0.3

    // MARK: - OpenDoor view interface requirements
    var presenter: OpenDoorViewDelegateInterface!
    
    // MARK: - View lifecycle -
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
    }
  
    // MARK: - Public functions -

    // MARK: - IBActions -
    @IBAction func openDoorButtonTouched() {
        presenter.didTouchEnterRoomButton()
    }
  
    // MARK: - Private functions -
}

// MARK: - Extensions -

extension OpenDoorViewController: OpenDoorViewInterface {
    func showErrorMessage(errorMessage: String) {
    }
    
    func setViewTitle(title: String) {
        self.title = title
    }

    func showErrorMessage(errorMessage: String, completionHandler: (() -> ())) {
        
    }
}
