//
//  LoginPresenter.swift
//  Door Opener
//
//  Created by Luka Usalj on 16/05/16.
//  Copyright (c) 2016 FER. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class LoginPresenter: NSObject {
    
    // MARK: - Private properties -
    private unowned var _view: LoginViewInterface
    private var _interactor: LoginInteractorInterface
    private var _wireframe: LoginWireframeInterface
    
    // MARK: - Lifecycle -
    init (wireframe: LoginWireframeInterface, view: LoginViewInterface, interactor: LoginInteractorInterface) {
        self._wireframe = wireframe
        self._view = view
        self._interactor = interactor
    }
}

extension LoginPresenter: LoginViewDelegateInterface {
    
    func didSelectNavigationAction(action: LoginNavigationAction) {
        _wireframe.performNavigationAction(action)
    }
    
    func didTouchReturnOnPasswordTextField() {
        guard let username = _view.username, password = _view.password else {
            _view.showErrorMessage("Please enter username and password", completionHandler: { [unowned self] in
                self._view.clearForm()
            })
            return
        }
        
        _view.showSpinner()
        
        _interactor.requestTokenForUserWith(username, password: password, success: { [weak self] (token) in
            self?._view.hideSpinner()
            TokenManager.token = token
            self?._wireframe.performNavigationAction(LoginNavigationAction.GoToDoorOpening)
            }) { [weak self] (error) in
                self?._view.hideSpinner()
                self?._view.showErrorMessage(error)
        }
    }
}
