//
//  LoginInterfaces.swift
//  Door Opener
//
//  Created by Luka Usalj on 16/05/16.
//  Copyright (c) 2016 FER. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import UIKit

// MARK: - Navigation -
enum  LoginNavigationAction {
    case GoToDoorOpening
}

// MARK: - Login Wireframe Interface -
protocol LoginWireframeInterface: WireframeInterface {
    func performNavigationAction(action: LoginNavigationAction)
    func configureModuleWith(viewController: LoginViewController)
}

// MARK: - Login View Interface -
protocol LoginViewInterface: ViewInterface {
    
    
    var username: String? {get}
    var password: String? {get}
    
    func clearForm()
}

// MARK: - Login View Presenter (Delegate) Interface -
protocol LoginViewDelegateInterface: PresenterInterface {
    func didSelectNavigationAction(action: LoginNavigationAction)
    func didTouchReturnOnPasswordTextField()
}

// MARK: - Login Interactor Interface -
protocol LoginInteractorInterface: InteractorInterface {
    func requestTokenForUserWith(username: String, password: String,
                                 success: (token: String) -> (),
                                 failure: (error: String) -> ())
}
