//
//  EnteredRoomInterfaces.swift
//  Door Opener
//
//  Created by Luka Usalj on 16/05/16.
//  Copyright (c) 2016 FER. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import UIKit

// MARK: - Navigation -
enum  EnteredRoomNavigationAction {
    case GoToOpenDoorScreen
    case GoToLoginScreen
}

// MARK: - EnteredRoom Wireframe Interface -
protocol EnteredRoomWireframeInterface: WireframeInterface {
    func performNavigationAction(action: EnteredRoomNavigationAction)
    func configureModuleWith(viewController: EnteredRoomViewController)
}

// MARK: - EnteredRoom View Interface -
protocol EnteredRoomViewInterface: ViewInterface {
}

// MARK: - EnteredRoom View Presenter (Delegate) Interface -
protocol EnteredRoomViewDelegateInterface: PresenterInterface {
    func didSelectNavigationAction(action: EnteredRoomNavigationAction)
    func didTouchLeaveRoom()
}

// MARK: - EnteredRoom Interactor Interface -
protocol EnteredRoomInteractorInterface: InteractorInterface {
    func leaveRoomWithID(roomID: String, token: String, success: () -> (), failure: (error: String) -> ())
}
