//
//  EnteredRoomViewController.swift
//  Door Opener
//
//  Created by Luka Usalj on 16/05/16.
//  Copyright (c) 2016 FER. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

// MARK: -  EnteredRoom View Controller -
final class EnteredRoomViewController: UIViewController {
    
    // MARK: - EnteredRoom view interface requirements
    var presenter: EnteredRoomViewDelegateInterface!
    
    // MARK: - View lifecycle -
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
    }
  
    // MARK: - Public functions -

    // MARK: - IBActions -
    @IBAction func leaveRoomButtonTouched() {
        presenter.didTouchLeaveRoom()
    }
  
    // MARK: - Private functions -
}

// MARK: - Extensions -

extension EnteredRoomViewController: EnteredRoomViewInterface {
    func showSpinner() {

    }

    func hideSpinner() {

    }

    func showErrorMessage(errorMessage: String) {

    }

    func showErrorMessage(errorMessage: String, completionHandler: (() -> ())) {
        
    }
}
