//
//  EnteredRoomWireframe.swift
//  Door Opener
//
//  Created by Luka Usalj on 16/05/16.
//  Copyright (c) 2016 FER. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import UIKit

struct EnteredRoomContext {
}

final class EnteredRoomWireframe: NSObject {
    
    // MARK: - Private properties -
    private var _context: EnteredRoomContext?
    private let _storyboard: UIStoryboard = UIStoryboard(name: "EnteredRoom", bundle: nil)
    
    // MARK: - Public properties -
    weak var navigationController: UINavigationController?
    weak var viewController: UIViewController?
    
    // MARK: - Init -
    private override init() {}

    init(context: EnteredRoomContext? = nil, navigationController: UINavigationController? = nil) {
        super.init()
        self._context = context
        self.navigationController = navigationController
    }
    
    // MARK: - Module setup -
    func instantiateAndConfigureModule() -> UIViewController {
        let moduleViewController = _storyboard.instantiateViewControllerWithIdentifier("EnteredRoomViewController") as! EnteredRoomViewController
        configureModuleWith(moduleViewController)
        viewController = moduleViewController
        return moduleViewController
    }
    
    func configureModuleWith(viewController: EnteredRoomViewController) {
        let interactor = EnteredRoomInteractor()
        let presenter = EnteredRoomPresenter(wireframe: self, view: viewController, interactor: interactor)
        viewController.presenter = presenter
    }
}

// MARK: - EnteredRoom Wireframe Interface Requirements -
extension EnteredRoomWireframe: EnteredRoomWireframeInterface {
    func performNavigationAction(action: EnteredRoomNavigationAction) {
        switch action {
        case .GoBack:
            navigationController?.popViewControllerAnimated(true)
        }
    }
}