//
//  EnteredRoomPresenter.swift
//  Door Opener
//
//  Created by Luka Usalj on 16/05/16.
//  Copyright (c) 2016 FER. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class EnteredRoomPresenter: NSObject {
    
    // MARK: - Private properties -
    private unowned var _view: EnteredRoomViewInterface
    private var _interactor: EnteredRoomInteractorInterface
    private var _wireframe: EnteredRoomWireframeInterface
    
    // MARK: - Lifecycle -
    init (wireframe: EnteredRoomWireframeInterface, view: EnteredRoomViewInterface, interactor: EnteredRoomInteractorInterface) {
        self._wireframe = wireframe
        self._view = view
        self._interactor = interactor
    }
    
}

extension EnteredRoomPresenter: EnteredRoomViewDelegateInterface {
    
    func didSelectNavigationAction(action: EnteredRoomNavigationAction) {
        _wireframe.performNavigationAction(action)
    }
    
    func didTouchLeaveRoom() {
        _view.showSpinner()
        
        _interactor.leaveRoomWithID(roomID, token: TokenManager.token, success: { [weak self] in
            self?._view.hideSpinner()
            self?._wireframe.performNavigationAction(EnteredRoomNavigationAction.GoBack)
            }) { [weak self] (error) in
                self?._view.showErrorMessage(error)
        }

    }
}
